from typing import List, Dict, Tuple

TEST_CASES: Dict[str, List[Tuple[str, str, float]]] = {
    "market_movements": [
        ("Bitcoin surges past $50,000, reaching new yearly high", "positive", 0.9),
        ("Ethereum crashes 20% in massive market selloff", "negative", 0.9),
        ("Bitcoin trading sideways around $45,000 support level", "neutral", 0.7),
        ("Crypto market cap drops below $1 trillion amid selling pressure", "negative", 0.8),
        ("Multiple cryptocurrencies post double-digit gains in market rally", "positive", 0.8),
        ("Bitcoin price explodes upward, breaking key resistance levels", "positive", 0.9),
        ("Market sentiment turns bearish as altcoins face heavy losses", "negative", 0.8),
        ("Cryptocurrency markets show stability after recent volatility", "neutral", 0.7),
        ("Major altcoins outperform Bitcoin in latest market surge", "positive", 0.8),
        ("Traders panic as market experiences flash crash", "negative", 0.9),
        ("Bitcoin briefly touches $60,000 before sharp reversal to $55,000", "neutral", 0.6),
        ("Ethereum leads market recovery despite earlier weakness", "positive", 0.7),
        ("Crypto market experiences mixed signals as Bitcoin dominance wanes", "neutral", 0.6),
        ("Digital assets face temporary setback amid broader market uncertainty", "negative", 0.6),
        ("Altcoin season gains momentum as Bitcoin consolidates gains", "positive", 0.7),
        ("Bitcoin breaks $110,000 milestone as institutional demand surges", "positive", 0.9),
        ("Bitcoin hits new ATH while Ethereum shows 20% YTD decline", "neutral", 0.7),
        ("Crypto market shows divergence as Bitcoin soars but altcoins lag", "neutral", 0.6),
        ("Multiple cryptocurrencies reach record highs in synchronized rally", "positive", 0.9),
        ("Market sentiment mixed as major coins show opposing trends", "neutral", 0.7),
        ("Bitcoin surpasses $120,000 as institutional demand reaches new heights", "positive", 0.9),
        ("Ethereum breaks $10,000 milestone amid Layer 2 adoption surge", "positive", 0.9),
        ("Market experiences 'super cycle' as multiple assets hit ATH simultaneously", "positive", 0.9),
        ("Bitcoin dominance falls below 40% as altcoins gain market share", "neutral", 0.6),
        ("Crypto market witnesses historic $100B liquidation event", "negative", 0.9),
        ("Bitcoin maintains $100,000 support level despite global market turbulence", "positive", 0.8),
        ("Digital asset market cap exceeds $5 trillion for first time", "positive", 0.9),
        ("Altcoin market shows resilience as Bitcoin consolidates above $110,000", "positive", 0.8),
        ("Crypto market faces correction as Bitcoin retreats from $130,000", "negative", 0.7),
        ("Market sentiment reaches extreme greed as prices hit record levels", "neutral", 0.6)
    ],
    
    "technical_analysis": [
        ("Bitcoin forms golden cross pattern on daily timeframe", "positive", 0.8),
        ("Death cross formation signals potential bearish trend", "negative", 0.8),
        ("BTC consolidating between $40,000 and $42,000 range", "neutral", 0.7),
        ("Multiple indicators suggest oversold conditions in crypto market", "positive", 0.7),
        ("RSI divergence hints at potential trend reversal", "neutral", 0.6),
        ("MACD indicator shows strong bullish momentum building", "positive", 0.8),
        ("Bitcoin breaks below 200-day moving average", "negative", 0.8),
        ("Volume profile indicates accumulation at support", "positive", 0.7),
        ("Bearish divergence forms on multiple timeframes", "negative", 0.8),
        ("Market structure remains neutral on weekly chart", "neutral", 0.7),
        ("Hidden bullish divergence spotted on 4-hour timeframe despite bearish candles", "positive", 0.6),
        ("Triple bottom pattern forms with declining volume, suggesting weak bearish momentum", "neutral", 0.7),
        ("EMA ribbon compression indicates potential volatility explosion", "neutral", 0.6),
        ("Ichimoku cloud turns bearish while RSI shows oversold bounce", "neutral", 0.6),
        ("Fibonacci extension levels align with historical resistance zones", "neutral", 0.7),
        ("Bitcoin weekly RSI reaches highest level in history", "positive", 0.8),
        ("Multiple timeframe analysis shows strong bullish continuation pattern", "positive", 0.8),
        ("Volume analysis indicates institutional accumulation at $100,000 level", "positive", 0.8),
        ("Technical indicators suggest overextended market conditions", "negative", 0.7),
        ("Ethereum forms rare triple bullish divergence on daily chart", "positive", 0.8),
        ("Market structure shows potential distribution pattern at ATH", "negative", 0.7),
        ("On-chain metrics reveal unprecedented institutional inflows", "positive", 0.9),
        ("Advanced chart patterns suggest potential market cycle peak", "negative", 0.8)
    ],
    
    "adoption_news": [
        ("Major bank launches institutional crypto custody service", "positive", 0.8),
        ("Tech giant integrates Bitcoin payments into payment platform", "positive", 0.9),
        ("Investment firm delays Bitcoin ETF application review", "negative", 0.7),
        ("Central bank announces CBDC development plans", "neutral", 0.6),
        ("Leading retailer now accepts cryptocurrency payments", "positive", 0.8),
        ("Fortune 500 company adds Bitcoin to corporate treasury", "positive", 0.9),
        ("Major payment processor enables crypto transactions", "positive", 0.8),
        ("Investment bank suspends crypto trading services", "negative", 0.8),
        ("Government agency explores blockchain applications", "neutral", 0.6),
        ("Popular app introduces cryptocurrency rewards program", "positive", 0.7),
        ("Traditional finance giant experiments with DeFi protocols while maintaining regulatory compliance", "positive", 0.7),
        ("Regional banks suspend crypto services pending regulatory clarity", "negative", 0.7),
        ("Gaming industry divided over blockchain integration amid user feedback", "neutral", 0.6),
        ("Enterprise blockchain adoption grows despite crypto market volatility", "positive", 0.7),
        ("Institutional investors maintain crypto positions while reducing active trading", "neutral", 0.6),
        ("Global investment banks launch crypto prime brokerage services", "positive", 0.9),
        ("Major sovereign wealth fund allocates 5% to digital assets", "positive", 0.9),
        ("Fortune 100 companies form blockchain adoption consortium", "positive", 0.8),
        ("Leading pension funds begin Bitcoin allocation programs", "positive", 0.9),
        ("International payment networks integrate Lightning Network", "positive", 0.8),
        ("Traditional finance platforms enable crypto staking services", "positive", 0.8),
        ("Major e-commerce platform enables global crypto payments", "positive", 0.8),
        ("Investment giants launch institutional DeFi products", "positive", 0.8)
    ],
    
    "regulatory_news": [
        ("SEC approves spot Bitcoin ETF applications", "positive", 0.9),
        ("Government announces crypto trading ban in major market", "negative", 0.9),
        ("Regulatory body proposes new crypto framework", "neutral", 0.6),
        ("Tax authority clarifies crypto reporting requirements", "neutral", 0.6),
        ("Regulators crack down on unregistered crypto exchanges", "negative", 0.8),
        ("New legislation supports cryptocurrency innovation", "positive", 0.8),
        ("Financial watchdog issues warning about crypto risks", "negative", 0.7),
        ("Regulatory sandbox launched for crypto companies", "positive", 0.7),
        ("Government considers stricter crypto regulations", "negative", 0.7),
        ("International coalition develops crypto standards", "neutral", 0.6),
        ("Mixed regulatory signals as authorities balance innovation with consumer protection", "neutral", 0.6),
        ("Regulatory framework faces criticism from both industry advocates and skeptics", "neutral", 0.6),
        ("Progressive jurisdiction creates crypto-friendly policies while maintaining oversight", "positive", 0.7),
        ("Global regulatory divergence creates compliance challenges for crypto firms", "negative", 0.7),
        ("Regulatory clarity emerges in key markets despite ongoing debates", "positive", 0.6),
        ("Multiple jurisdictions pass favorable stablecoin regulations", "positive", 0.8),
        ("State government establishes bitcoin reserves amid federal scrutiny", "positive", 0.7),
        ("Legislative bodies advance crypto-friendly bills with strong majority", "positive", 0.8),
        ("Regional authorities compete to establish crypto-friendly frameworks", "positive", 0.7),
        ("Stablecoin regulation gains clarity across major financial hubs", "positive", 0.8),
        ("Global regulatory framework for DeFi platforms emerges", "positive", 0.8),
        ("Central banks coordinate on crypto regulatory standards", "positive", 0.7),
        ("Major economy introduces comprehensive crypto licensing system", "positive", 0.8),
        ("International task force proposes unified crypto taxation framework", "neutral", 0.6),
        ("Regulators approve crypto derivatives for pension funds", "positive", 0.8),
        ("New legislation enables tokenized securities trading", "positive", 0.8),
        ("Banking regulators set crypto exposure guidelines", "neutral", 0.6),
        ("Cross-border crypto payment framework established", "positive", 0.8)
    ],
    
    "defi_and_nft": [
        ("Major DeFi protocol reaches $10B in total value locked", "positive", 0.8),
        ("NFT trading volume hits record high on leading marketplace", "positive", 0.8),
        ("DeFi protocol suffers smart contract exploit", "negative", 0.9),
        ("NFT floor prices decline across major collections", "negative", 0.7),
        ("New yield farming program launches with high APY", "positive", 0.7),
        ("DeFi protocol introduces innovative staking mechanism", "positive", 0.8),
        ("NFT project reveals successful community governance", "positive", 0.7),
        ("Liquidity mining rewards reduced across protocols", "negative", 0.7),
        ("Cross-chain bridge suffers security incident", "negative", 0.9),
        ("DeFi insurance platform expands coverage options", "positive", 0.7),
        ("Layer-2 DeFi protocols show growth despite main chain congestion", "positive", 0.7),
        ("NFT market sentiment shifts towards utility-focused projects", "neutral", 0.6),
        ("DeFi governance proposals reveal community division over protocol direction", "neutral", 0.6),
        ("Hybrid NFT-DeFi platforms emerge with mixed initial adoption", "neutral", 0.6),
        ("Cross-chain DeFi activity increases despite bridge security concerns", "neutral", 0.7),
        ("Institutional DeFi protocol surpasses $50B in TVL", "positive", 0.9),
        ("Real-world asset tokenization platform launches successfully", "positive", 0.8),
        ("Major bank launches regulated DeFi lending platform", "positive", 0.9),
        ("NFT marketplace introduces institutional trading features", "positive", 0.8),
        ("DeFi insurance protocol covers $10B in assets", "positive", 0.8),
        ("Traditional finance assets enter DeFi ecosystem", "positive", 0.8),
        ("Cross-chain DeFi protocol achieves regulatory compliance", "positive", 0.8),
        ("NFT infrastructure enables enterprise adoption", "positive", 0.8)
    ],
    
    "security_and_technology": [
        ("Cryptocurrency exchange suffers major security breach", "negative", 0.9),
        ("Layer-2 solution achieves new scalability milestone", "positive", 0.8),
        ("Network upgrade successfully implements new features", "positive", 0.7),
        ("Mining difficulty adjusts following hashrate changes", "neutral", 0.7),
        ("Critical vulnerability discovered in smart contract", "negative", 0.9),
        ("New privacy protocol enhances transaction security", "positive", 0.8),
        ("Blockchain network completes successful hard fork", "positive", 0.7),
        ("Security audit reveals minor protocol vulnerabilities", "negative", 0.7),
        ("Network stress test demonstrates robust performance", "positive", 0.8),
        ("Emergency patch deployed to fix consensus issue", "negative", 0.8),
        ("Zero-knowledge proof implementation shows promise despite complexity", "positive", 0.7),
        ("Novel consensus mechanism faces scalability vs security tradeoffs", "neutral", 0.6),
        ("Quantum computing developments raise long-term cryptographic concerns", "negative", 0.7),
        ("Multi-chain infrastructure improves despite occasional cross-chain issues", "neutral", 0.6),
        ("Security researchers identify theoretical attack vector with low probability", "neutral", 0.6),
        ("Zero-knowledge scaling solution achieves mainstream adoption", "positive", 0.8),
        ("New consensus mechanism demonstrates enterprise scalability", "positive", 0.8),
        ("Quantum-resistant cryptography implemented on major blockchain", "positive", 0.8),
        ("Layer-2 solutions achieve sub-second finality", "positive", 0.8),
        ("Cross-chain security protocol prevents bridge exploits", "positive", 0.8),
        ("AI-powered security system prevents smart contract attacks", "positive", 0.8),
        ("Blockchain achieves 1 million TPS in stress test", "positive", 0.8),
        ("New privacy protocol receives security certification", "positive", 0.8)
    ],
    
    "complex_scenarios": [
        ("Bitcoin mining difficulty increases while hash rate drops temporarily", "neutral", 0.6),
        ("DeFi protocol TVL grows despite declining token price", "neutral", 0.7),
        ("Institutional adoption continues amid retail market correction", "positive", 0.7),
        ("Technical indicators conflict with on-chain metrics", "neutral", 0.6),
        ("Market makers increase activity during low liquidity periods", "neutral", 0.6),
        ("Derivatives market shows bullish bias despite spot market weakness", "neutral", 0.6),
        ("Protocol upgrade successful but token price reacts negatively", "neutral", 0.7),
        ("Long-term holders accumulate while short-term metrics decline", "neutral", 0.6),
        ("Ecosystem growth continues despite main token underperformance", "neutral", 0.7),
        ("Cross-chain metrics reveal diverging market dynamics", "neutral", 0.6),
        ("Regulatory compliance improves but restricts certain protocol features", "neutral", 0.6),
        ("Layer-2 adoption grows while Layer-1 congestion persists", "positive", 0.7),
        ("DEX volumes increase despite CEX market share dominance", "positive", 0.7),
        ("Smart money flows indicate accumulation despite retail fear", "positive", 0.7),
        ("On-chain metrics strengthen while market sentiment remains fearful", "neutral", 0.6),
        ("Bitcoin reaches ATH while altcoin market shows weakness", "neutral", 0.7),
        ("ETF market activity drives price discovery amid mixed market signals", "positive", 0.7),
        ("Spot Bitcoin ETFs break out while crypto stocks show varied performance", "positive", 0.8),
        ("Multiple positive catalysts emerge despite underlying market divergence", "positive", 0.7),
        ("Institutional products gain traction while retail sentiment remains cautious", "neutral", 0.6),
        ("ETF inflows reach record high while spot markets show divergence", "positive", 0.7),
        ("Institutional derivatives demand surges amid spot market consolidation", "positive", 0.7),
        ("Market makers adjust to new price discovery mechanisms post-ETF", "neutral", 0.6),
        ("Cross-border settlement volumes increase despite regulatory hurdles", "positive", 0.7),
        ("DeFi-CeFi hybrid platforms gain institutional adoption", "positive", 0.8),
        ("Layer-2 ecosystem flourishes while Layer-1 fees stabilize", "positive", 0.7),
        ("Tokenized real-world assets integrate with DeFi protocols", "positive", 0.8),
        ("Institutional staking services expand despite technical challenges", "positive", 0.7)
    ]
}

def get_all_test_cases() -> List[Tuple[str, str, float]]:
    """Return all test cases as a flat list"""
    all_cases = []
    for category, cases in TEST_CASES.items():
        all_cases.extend(cases)
    return all_cases

def get_category_cases(category: str) -> List[Tuple[str, str, float]]:
    """Return test cases for a specific category"""
    return TEST_CASES.get(category, []) 